# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-21 22:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_auto_20180518_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='pw_hash',
            field=models.CharField(default='defaultpw', max_length=255),
            preserve_default=False,
        ),
    ]
